package coursework.appointments.model;

import java.util.Date;

import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAttribute;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;

import coursework.appointments.constants.ConfigDB;

@DynamoDBTable(tableName=ConfigDB.DYNAMODB_TABLE_NAME)
public class Appointment {
	private String userId;
	private String appointmentId;
	private String title;
	private String owner;
	private Date dateTime;
	private int durationInMinutes;
	private String description;	

	public Appointment() {}
	
	public Appointment(String userId, String title, Date dateTime, String owner, int durationInMinutes,
			String description) {
		this.setOwner(owner);
		this.setUserId(userId);
		this.setTitle(title);
		this.setDateTime(dateTime);
		this.setDurationInMinutes(durationInMinutes);
		this.setDescription(description);
	}
	@DynamoDBAttribute(attributeName = "owner")
	public String getOwner() {
		return owner;
	}

	public void setOwner(String owner) {
		this.owner = owner;
	}

	@DynamoDBHashKey(attributeName = "userId")
	public String getUserId() {
		return userId;
	}

	public void setUserId(String userId) {
		this.userId = userId;
	}
	
	@DynamoDBHashKey(attributeName = "appointmentId")
	@DynamoDBAutoGeneratedKey
	public String getAppointmentId() {
		return appointmentId;
	}

	public void setAppointmentId(String appointmentId) {
		this.appointmentId = appointmentId;
	}
	
	@DynamoDBAttribute(attributeName = "title")
	public String getTitle() {
		return title;
	}

	public void setTitle(String title) {
		this.title = title;
	}

	@DynamoDBAttribute(attributeName = "dateAndTime")
	public Date getDateTime() {
		return dateTime;
	}

	public void setDateTime(Date dateTime) {
		this.dateTime = dateTime;
	}

	@DynamoDBAttribute(attributeName = "duration")
	public int getDurationInMinutes() {
		return durationInMinutes;
	}

	public void setDurationInMinutes(int durationInMinutes) {
		this.durationInMinutes = durationInMinutes;
	}

	@DynamoDBAttribute(attributeName = "description")
	public String getDescription() {
		return description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	@Override
	public String toString() {
		return "Appointment [userId=" + userId + ", appointmentId=" + appointmentId + ", title=" + title + ", dateTime="
				+ dateTime + ", durationInMinutes=" + durationInMinutes + ", description=" + description + "]";
	}
	
	
}
